---
- name: DOCKER - Install packages needed to use a repository over HTTPS
  apt:
          name: "{{ item }}"
          state: latest
  with_items:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

- name: DOCKER - Add Docker's official GPG key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

- name: DOCKER - Add official Docker repo
  apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
          state: present

- name: DOCKER - Update apt
  apt: 
          update_cache: yes

- name: DOCKER - Install Docker packages
  apt: 
          name: "{{ item }}"
          state: latest
  with_items:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose

- name: DOCKER - Enable docker service on boot
  systemd:
          name: docker
          enabled: true
          state: started
