---
- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes

- name: Ensure Iptables is installed
  yum:
    name: iptables-services
    state: present

- name: Enable iptables service
  systemd:
    name: iptables
    state: started
    enabled: yes

- name: Include Iptables tasks
  include_tasks: iptables.yml