---
- name: Change hostname
  hostname:
          name: "{{ inventory_hostname }}"
          
- name: Include distro specific tasks
  include_tasks: "{{ ansible_distribution|lower }}.yml"

- name: Include SSH tasks
  include_tasks: ssh.yml

- name: Include iptables tasks
  include_tasks: iptables.yml

- name: Include Fail2Ban tasks
  include_tasks: fail2ban.yml

- name: Include Docker tasks
  include_tasks: docker.yml

- name: Include OpenVPN tasks
  include_tasks: openvpn.yml

- name: Include Netdata tasks
  include_tasks: netdata.yml

- name: Include NFS tasks
  include_tasks: nfs.yml

- name: Rebooting
  reboot:
