---
- name: Wait up to 600 seconds until host is ready
  wait_for_connection:

- name: Gather facts
  setup:

- name: Change hostname
  hostname:
          name: "{{ inventory_hostname }}"
          
- name: Include distro specific tasks
  include_tasks: "{{ ansible_distribution|lower }}.yml"

- name: Include SSH tasks
  include_tasks: ssh.yml

- name: Rebooting
  reboot:
