---
- name: MAIN - Install aptitude
  apt:
          name: aptitude
          state: latest

- name: MAIN - Colorize bash prompt
  lineinfile:
          path: /root/bashrc
          regexp: '^#force_color_prompt=yes'
          line: 'force_color_prompt=yes'

- name: MAIN - Update
  apt:
          name: "*"
          state: latest

- name: MAIN - Install packages
  apt:
          name: "{{item}}"
          state: latest
  with_items:
          - htop
          - screen
          - vim
          - git
          - curl

- name: MAIN - Include SSH tasks
  include_tasks: ssh.yml

- name: MAIN - Include iptables tasks
  include_tasks: iptables.yml

- name: MAIN - Include Fail2Ban tasks
  include_tasks: fail2ban.yml

- name: MAIN - Include Docker tasks
  include_tasks: docker.yml

- name: MAIN - Include OpenVPN tasks
  include_tasks: openvpn.yml
