---
- name: MAIN - Update
  apt:
          name: "*"
          state: latest

- name: MAIN - Install packages
  apt:
          name: "{{item}}"
          state: latest
  with_items:
          - htop
          - screen
          - vim
          - git
          - curl

- name: MAIN - Include SSH tasks
  include_tasks: ssh.yml

- name: MAIN - Include iptables tasks
  include_tasks: iptables.yml

