---
- name: Add OpenVPN apt key
  apt_key:
          url: https://swupdate.openvpn.net/repos/repo-public.gpg
          state: present
  when: ansible_os_family == "Debian"

- name: Add OpenVPN repository
  apt_repository:
          repo: "deb http://build.openvpn.net/debian/openvpn/stable {{ ansible_distribution_release }} main"
          state: present
  when: ansible_os_family == "Debian"

- name: Install OpenVPN from official repo
  apt:
          name: openvpn
          state: latest
          update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure epel is installed 
  yum:
          name: epel-release
          state: latest
  when: ansible_os_family == "RedHat"

- name: Install OpenVPN with YUM
  yum:
          name: "{{ packages }}"
          state: latest
  vars:
          packages:
                  - openvpn
                  - wget
  when: ansible_os_family == "RedHat"


- name: Download EasyRSA
  get_url:
          url: "{{ easy_rsa_url }}"
          dest: /tmp/easyrsa.tgz

- name: Unpack EasyRSA tarball
  unarchive:
          src: /tmp/easyrsa.tgz
          dest: /etc/openvpn/
          remote_src: yes

- name: Delete tarball
  file:
          path: /tmp/easyrsa.tgz
          state: absent

- name: Template vars file
  template:
          src: templates/vars.j2
          dest: /etc/openvpn/EasyRSA-v3.0.6/vars

- block:
        - name: Initiate public key infrastructure
          command: "./easyrsa init-pki"
          args:
                  chdir: /etc/openvpn/EasyRSA-v3.0.6/
                  creates: pki

        - name: Build CA
          command: "./easyrsa build-ca nopass"
          args:
                  chdir: /etc/openvpn/EasyRSA-v3.0.6/
                  creates: pki/ca.crt
        
        - name: Generate server request files
          command: "./easyrsa gen-req {{ inventory_hostname }}-vpn-server nopass"
          args:
                  chdir: /etc/openvpn/EasyRSA-v3.0.6/
                  creates: pki/private/server.key
        
        - name: Copy server key file to OpenVPN directory
          copy:
                  src: "/etc/openvpn/EasyRSA-v3.0.6/pki/private/{{ inventory_hostname }}-vpn-server.key"
                  dest: /etc/openvpn
                  remote_src: yes
  environment:
          EASYRSA_BATCH: 1

