---
- name: Update 
  yum:
          name: "*"
          state: latest

- name: Install epel-release
  yum:
          name: epel-release
          state: latest

- name: Install packages
  yum:
          name: "{{ packages }}"
          state: latest
  vars:
          packages:
                  - htop
                  - screen
                  - vim
                  - git
                  - curl
                  - unzip

- name: Include yum-cron tasks
  include_tasks: yum-cron.yml

- name: Include Firewalld tasks
  include_tasks: firewalld.yml
