---
- name: YUM update
  yum:
    name: "*"
    state: latest

- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install packages
  yum:
    name: "{{ common_packages + redhat_packages}}"
    state: latest

- name: Include yum-cron tasks
  include_tasks: yum-cron.yml

- name: Include Firewalld tasks
  include_tasks: firewalld.yml
