---
- name: Disallow SSH password connections
  lineinfile:
          path: /etc/ssh/sshd_config
          regexp: '^PermitRootLogin'
          line: 'PermitRootLogin without-password'
  
- name: Restart SSH service
  systemd:
          name: sshd
          state: restarted
  
