---
- name: Install aptitude
  apt:
          name: aptitude
          state: latest
  when:
          - ansible_facts['distribution'] == "Ubuntu"

- name: Update APT
  apt:
          name: "*"
          state: latest

- name: Install packages
  apt:
          name: "{{ packages }}"
          state: latest
  vars:
          packages:
                  - htop
                  - screen
                  - vim
                  - git
                  - curl
                  - nfs-common
                  - unattended-upgrades

- name: Copy unattended-upgrades configuration files
  copy:
          src: "files/{{ item }}"
          dest: "/etc/apt/apt.conf.d/{{ item }}"
          mode: 0644
  with_items:
          - 50unattended-upgrades
          - 20auto-upgrades

- name: Restart unattended-upgrades service
  systemd:
          name: unattended-upgrades
          state: restarted

